---
name: ((deployment_name))

instance_groups:
  - name: traefik
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
          bpm:
            enabled: true
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: traefik
    stemcell: default
    vm_type: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: ((network_name))

variables:
  - name: traefik_ca
    type: certificate
    options:
      is_ca: true
      common_name: Traefik CA
    update_mode: converge

  - name: traefik_tls
    type: certificate
    options:
      ca: traefik_ca
      common_name: ((traefik_domain))
      alternative_names:
        - ((traefik_domain))
        - "*.((traefik_domain))"
    update_mode: converge

features:
  use_dns_addresses: true

update:
  serial: false

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: traefik
  sha1: a02e206ca0c1a5e493ea14cca1e3e828101d064f
  stemcell:
    os: ubuntu-xenial
    version: "621.29"
  url: https://s3.eu-west-3.amazonaws.com/traefik-boshrelease/compiled-releases/traefik/traefik-1.11.0-ubuntu-xenial-621.29-20191211-002326-374535001-20191211002327.tgz
  version: 1.11.0
- name: bpm
  sha1: e7d474c3a205fa4438ea5a60d3b59479939163aa
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.7
  version: 1.1.7
