---
name: ((deployment_name))

instance_groups:
  - name: traefik
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
          bpm:
            enabled: true
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: traefik
    stemcell: default
    vm_type: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: ((network_name))

variables:
  - name: traefik_ca
    type: certificate
    options:
      is_ca: true
      common_name: Traefik CA
    update_mode: converge

  - name: traefik_tls
    type: certificate
    options:
      ca: traefik_ca
      common_name: ((traefik_domain))
      alternative_names:
        - ((traefik_domain))
        - "*.((traefik_domain))"
    update_mode: converge

features:
  use_dns_addresses: true

update:
  serial: false

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: traefik
  sha1: 8126944245f363141f444ff4a195f227ca36ee3d
  stemcell:
    os: ubuntu-xenial
    version: "621.59"
  url: https://s3.eu-west-3.amazonaws.com/traefik-boshrelease/compiled-releases/traefik/traefik-1.12.0-ubuntu-xenial-621.59-20200306-164943-023591201-20200306164944.tgz
  version: 1.12.0
- name: bpm
  sha1: c956394fce7e74f741e4ae8c256b480904ad5942
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
  version: 1.1.8
